services:
  redis:
    image: redis:7-alpine
    container_name: ntop_redis
    restart: unless-stopped
    volumes:
      - redis_data:/data

  ntopng:
    image: ntop/ntopng:latest
    container_name: ntopng
    restart: unless-stopped
    depends_on:
      - redis
    environment:
      - TZ=America/Santiago
      - NTOP_PERSISTENCE=1
      - REDIS_HOST=redis
    ports:
      - "3000:3000" # UI
      - "5556:5556" # API
    volumes:
      - ntop_data:/data
    #command: ["--redis", "redis:6379"]
    command: ["--redis", "redis:6379", "--http-server-auth-type", "none"]

  influxdb:
    image: influxdb:2.7
    container_name: influxdb
    restart: unless-stopped
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=changeme_influx
      - DOCKER_INFLUXDB_INIT_ORG=home
      - DOCKER_INFLUXDB_INIT_BUCKET=nmap_bucket
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=supersecrettoken
    ports:
      - "8086:8086"
    volumes:
      - influx_data:/var/lib/influxdb2

  grafana:
    image: grafana/grafana-oss:10.0.0
    container_name: grafana
    restart: unless-stopped
    depends_on:
      - influxdb
      - ntopng
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=changeme_grafana
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
      - GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS=vonage-status-panel
    ports:
      - "3001:3000"
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/dashboards:/var/lib/grafana/dashboards

  nmap-scanner:
    build:
      context: ./nmap-scanner
      dockerfile: Dockerfile
    container_name: nmap_scanner
    restart: unless-stopped
    depends_on:
      - influxdb
    environment:
      - TZ=America/Santiago
      - TARGET_NETWORK=192.168.1.0/24
      - SCAN_SCHEDULE=0 */6 * * *
      - TOPOLOGY_SCHEDULE=0 */12 * * *
      - INFLUX_URL=http://influxdb:8086 # Cambiar de localhost a hostname
      - INFLUX_TOKEN=supersecrettoken
      - INFLUX_ORG=home
      - INFLUX_BUCKET=nmap_bucket
      - HTTP_PORT=8080
      - SCAN_TIMEOUT=900
      - RUN_INITIAL_SCAN=false
    ports:
      - "8082:8080" # Mapeo normal de puertos
    volumes:
      - scan_results:/results
    cap_add:
      - NET_RAW
      - NET_ADMIN
    # network_mode: host  # Comentar esta línea
    privileged: true # Agregar esto para permisos de red

  ntopng-collector:
    build:
      context: ./ntopng-collector
      dockerfile: Dockerfile
    container_name: ntopng_collector
    restart: unless-stopped
    depends_on:
      - ntopng
      - influxdb
    environment:
      - TZ=America/Santiago
      - NTOPNG_URL=http://ntopng:3000
      - NTOPNG_USER=admin
      - NTOPNG_PASSWORD=admin
      - INFLUX_URL=http://influxdb:8086
      - INFLUX_TOKEN=supersecrettoken
      - INFLUX_ORG=home
      - INFLUX_BUCKET=nmap_bucket
      - COLLECTION_INTERVAL=300
    command: >
      sh -c "
        echo 'Esperando que InfluxDB esté completamente listo...' &&
        sleep 45 &&
        python3 src/ntopng_collector.py
      "

  topology-viewer:
    build:
      context: ./topology-viewer
      dockerfile: Dockerfile
    container_name: topology_viewer
    restart: unless-stopped
    depends_on:
      - nmap-scanner
    ports:
      - "8083:80"
    volumes:
      - scan_results:/usr/share/nginx/html/results:ro

volumes:
  redis_data:
  ntop_data:
  influx_data:
  scan_results:
