apiVersion: 1
datasources:
  - name: InfluxDB
    type: influxdb
    access: proxy
    orgId: 1
    url: http://influxdb:8086
    jsonData:
      version: Flux
      organization: home
      defaultBucket: nmap_bucket
      tlsSkipVerify: true
    secureJsonData:
      token: supersecrettoken
    isDefault: true
